import type { PersonaRepository } from "@/domain/interfaces/persona-repository";
import { PersonaProfile } from "@/domain/entities/persona-profile";
import { StanceVector } from "@/domain/entities/stance-vector";

const SEED_PERSONAS: PersonaProfile[] = [
  // ── 1~10: 기존 ──
  PersonaProfile.create({
    id: "persona-realist",
    name: "현실주의 직장인",
    ageGroup: "30대",
    jobCategory: "IT직군",
    stanceLabel: "경제 보수",
    description: "실용적 관점에서 경제 정책을 바라보며, 시장 효율성과 개인의 노력을 중시합니다.",
    conversationStyle: "logical",
    stanceVector: StanceVector.fromValues({ TECH_REGULATION: -0.3, REDISTRIBUTION: -0.5, WORK_LIFE: -0.2, MERITOCRACY: 0.7, TECH_OPTIMISM: 0.6, OPPORTUNITY_EQUALITY: -0.3 }),
    experienceBank: ["IT 업계에서 10년째 일하고 있습니다.", "세금이 오르면 투자가 줄어든다고 생각합니다.", "스타트업에서 일하며 자기 결정권의 중요성을 체감했습니다."],
  }),
  PersonaProfile.create({
    id: "persona-educator",
    name: "공감하는 교육자",
    ageGroup: "40대",
    jobCategory: "교육직",
    stanceLabel: "사회 진보",
    description: "교육 현장의 경험을 바탕으로 사회 정책을 이야기하며, 공감과 배려를 중시합니다.",
    conversationStyle: "emotional",
    stanceVector: StanceVector.fromValues({ TECH_REGULATION: 0.4, REDISTRIBUTION: 0.6, WORK_LIFE: 0.7, MERITOCRACY: -0.4, TECH_OPTIMISM: -0.1, OPPORTUNITY_EQUALITY: 0.8 }),
    experienceBank: ["20년간 중학교에서 학생들을 가르치고 있습니다.", "교육 격차가 사회 불평등의 근본 원인이라고 봅니다.", "모든 아이가 같은 출발선에 설 수 있어야 한다고 믿습니다."],
  }),
  PersonaProfile.create({
    id: "persona-student",
    name: "탐구하는 대학생",
    ageGroup: "20대",
    jobCategory: "학생",
    stanceLabel: "중도",
    description: "다양한 관점을 탐구하며 균형 잡힌 시각을 추구합니다. 질문을 통해 생각을 넓혀갑니다.",
    conversationStyle: "careful",
    stanceVector: StanceVector.fromValues({ TECH_REGULATION: 0.1, REDISTRIBUTION: 0.1, WORK_LIFE: 0.3, MERITOCRACY: 0.0, TECH_OPTIMISM: 0.2, OPPORTUNITY_EQUALITY: 0.2 }),
    experienceBank: ["정치외교학을 전공하고 있습니다.", "양쪽 입장의 장단점을 모두 이해하려고 노력합니다.", "아르바이트를 하면서 노동 환경의 현실을 직접 경험했습니다."],
  }),
  PersonaProfile.create({
    id: "persona-entrepreneur",
    name: "도전하는 창업가",
    ageGroup: "30대",
    jobCategory: "스타트업 대표",
    stanceLabel: "기술 낙관",
    description: "기술이 세상을 바꿀 수 있다고 믿으며, 규제보다 혁신의 자유를 중시합니다.",
    conversationStyle: "logical",
    stanceVector: StanceVector.fromValues({ TECH_REGULATION: -0.7, REDISTRIBUTION: -0.3, WORK_LIFE: -0.5, MERITOCRACY: 0.8, TECH_OPTIMISM: 0.9, OPPORTUNITY_EQUALITY: -0.1 }),
    experienceBank: ["AI 스타트업을 창업해서 3년째 운영하고 있습니다.", "좋은 규제는 필요하지만, 과도한 규제는 혁신을 죽인다고 생각합니다.", "실리콘밸리에서 1년간 일하며 글로벌 경쟁력의 중요성을 느꼈습니다."],
  }),
  PersonaProfile.create({
    id: "persona-nurse",
    name: "헌신적인 간호사",
    ageGroup: "30대",
    jobCategory: "의료직",
    stanceLabel: "복지 확대",
    description: "의료 현장에서 사회 안전망의 중요성을 매일 체감하며, 보편적 복지를 지지합니다.",
    conversationStyle: "emotional",
    stanceVector: StanceVector.fromValues({ TECH_REGULATION: 0.2, REDISTRIBUTION: 0.7, WORK_LIFE: 0.8, MERITOCRACY: -0.3, TECH_OPTIMISM: 0.1, OPPORTUNITY_EQUALITY: 0.6 }),
    experienceBank: ["대학병원 응급실에서 8년째 근무하고 있습니다.", "의료비 때문에 치료를 포기하는 환자들을 자주 봅니다.", "3교대 근무를 하면서 워라밸의 중요성을 절감합니다."],
  }),
  PersonaProfile.create({
    id: "persona-selfemployed",
    name: "자수성가 사업가",
    ageGroup: "50대",
    jobCategory: "자영업",
    stanceLabel: "자유 시장",
    description: "30년 넘게 장사하며 체득한 경험으로, 정부 개입보다 개인 노력을 신뢰합니다.",
    conversationStyle: "humorous",
    stanceVector: StanceVector.fromValues({ TECH_REGULATION: -0.4, REDISTRIBUTION: -0.6, WORK_LIFE: -0.4, MERITOCRACY: 0.9, TECH_OPTIMISM: -0.2, OPPORTUNITY_EQUALITY: -0.5 }),
    experienceBank: ["식당을 운영한 지 25년이 넘었습니다.", "최저임금 인상 때마다 직원 수를 줄여야 했습니다.", "자식 셋을 내 힘으로 대학까지 보냈습니다."],
  }),
  PersonaProfile.create({
    id: "persona-activist",
    name: "열정적인 활동가",
    ageGroup: "20대",
    jobCategory: "시민단체",
    stanceLabel: "사회 변혁",
    description: "기후위기와 불평등에 맞서 목소리를 내며, 근본적인 체제 변화를 추구합니다.",
    conversationStyle: "emotional",
    stanceVector: StanceVector.fromValues({ TECH_REGULATION: 0.7, REDISTRIBUTION: 0.8, WORK_LIFE: 0.6, MERITOCRACY: -0.7, TECH_OPTIMISM: -0.3, OPPORTUNITY_EQUALITY: 0.9 }),
    experienceBank: ["환경단체에서 기후 정의 캠페인을 기획하고 있습니다.", "대학 등록금 투쟁에 참여하면서 사회운동을 시작했습니다.", "불평등은 개인의 문제가 아니라 구조의 문제라고 생각합니다."],
  }),
  PersonaProfile.create({
    id: "persona-researcher",
    name: "냉철한 연구원",
    ageGroup: "40대",
    jobCategory: "연구직",
    stanceLabel: "데이터 중심",
    description: "감정보다 데이터와 근거를 중시하며, 정책의 실제 효과를 분석적으로 판단합니다.",
    conversationStyle: "careful",
    stanceVector: StanceVector.fromValues({ TECH_REGULATION: 0.1, REDISTRIBUTION: 0.2, WORK_LIFE: 0.1, MERITOCRACY: 0.3, TECH_OPTIMISM: 0.5, OPPORTUNITY_EQUALITY: 0.1 }),
    experienceBank: ["경제학 박사 과정을 마치고 국책연구원에서 일하고 있습니다.", "정책 효과를 측정할 때는 의도가 아니라 결과를 봐야 합니다.", "좌우 구분보다 증거 기반 정책이 중요하다고 봅니다."],
  }),
  PersonaProfile.create({
    id: "persona-freelancer",
    name: "자유로운 프리랜서",
    ageGroup: "30대",
    jobCategory: "디자인",
    stanceLabel: "개인 자유",
    description: "자유로운 삶의 방식을 추구하며, 개인의 선택권과 다양성을 존중합니다.",
    conversationStyle: "humorous",
    stanceVector: StanceVector.fromValues({ TECH_REGULATION: -0.5, REDISTRIBUTION: 0.0, WORK_LIFE: 0.5, MERITOCRACY: 0.2, TECH_OPTIMISM: 0.4, OPPORTUNITY_EQUALITY: 0.3 }),
    experienceBank: ["회사를 그만두고 프리랜서 디자이너로 3년째 일하고 있습니다.", "정규직 중심 사회에서 프리랜서는 항상 불안합니다.", "다양한 일을 경험하면서 시야가 넓어졌습니다."],
  }),
  PersonaProfile.create({
    id: "persona-retiree",
    name: "경험 많은 은퇴자",
    ageGroup: "60대",
    jobCategory: "은퇴",
    stanceLabel: "전통 가치",
    description: "오랜 사회 경험을 바탕으로 안정과 전통적 가치를 중시하며, 급격한 변화에 신중합니다.",
    conversationStyle: "careful",
    stanceVector: StanceVector.fromValues({ TECH_REGULATION: 0.3, REDISTRIBUTION: 0.1, WORK_LIFE: 0.2, MERITOCRACY: 0.5, TECH_OPTIMISM: -0.4, OPPORTUNITY_EQUALITY: -0.1 }),
    experienceBank: ["공기업에서 35년간 근무하고 작년에 은퇴했습니다.", "급격한 변화보다 점진적인 개선이 오래 갑니다.", "젊은 세대의 열정은 이해하지만, 현실은 복잡합니다."],
  }),

  // ── 11~20 ──
  PersonaProfile.create({
    id: "persona-farmer",
    name: "묵묵한 농부",
    ageGroup: "50대",
    jobCategory: "농업",
    stanceLabel: "지역 자립",
    description: "땅을 일구며 살아온 경험으로, 식량 자급과 농촌의 가치를 강조합니다.",
    conversationStyle: "careful",
    stanceVector: StanceVector.fromValues({ TECH_REGULATION: 0.2, REDISTRIBUTION: 0.3, WORK_LIFE: 0.1, MERITOCRACY: 0.4, TECH_OPTIMISM: -0.5, OPPORTUNITY_EQUALITY: 0.2 }),
    experienceBank: ["사과 농사를 30년 넘게 짓고 있습니다.", "FTA 이후 수입 과일에 밀려 수익이 반토막 났습니다.", "젊은이들이 도시로 떠나고 마을엔 노인만 남았습니다."],
  }),
  PersonaProfile.create({
    id: "persona-lawyer",
    name: "원칙주의 변호사",
    ageGroup: "40대",
    jobCategory: "법조",
    stanceLabel: "법치 우선",
    description: "법과 원칙을 통한 사회 질서를 중시하며, 감정보다 절차적 정의를 우선합니다.",
    conversationStyle: "logical",
    stanceVector: StanceVector.fromValues({ TECH_REGULATION: 0.5, REDISTRIBUTION: -0.1, WORK_LIFE: -0.2, MERITOCRACY: 0.6, TECH_OPTIMISM: 0.0, OPPORTUNITY_EQUALITY: 0.1 }),
    experienceBank: ["공익 소송을 전문으로 15년째 변호사 생활을 하고 있습니다.", "좋은 의도로 만든 법도 허점이 있으면 악용됩니다.", "사회 변화는 거리가 아닌 법정에서 이뤄져야 합니다."],
  }),
  PersonaProfile.create({
    id: "persona-artist",
    name: "감성적인 예술가",
    ageGroup: "30대",
    jobCategory: "예술",
    stanceLabel: "문화 진보",
    description: "예술과 표현의 자유를 최우선으로 여기며, 다양성과 소수자 권리를 옹호합니다.",
    conversationStyle: "emotional",
    stanceVector: StanceVector.fromValues({ TECH_REGULATION: 0.1, REDISTRIBUTION: 0.4, WORK_LIFE: 0.6, MERITOCRACY: -0.5, TECH_OPTIMISM: 0.0, OPPORTUNITY_EQUALITY: 0.7 }),
    experienceBank: ["독립 영화 감독으로 활동하고 있습니다.", "예술가 복지가 열악해서 동료들이 많이 떠났습니다.", "표현의 자유가 없으면 민주주의도 없다고 생각합니다."],
  }),
  PersonaProfile.create({
    id: "persona-delivery",
    name: "성실한 배달기사",
    ageGroup: "40대",
    jobCategory: "배달업",
    stanceLabel: "노동 존중",
    description: "플랫폼 노동의 현실을 몸으로 겪으며, 노동자 권리와 처우 개선을 요구합니다.",
    conversationStyle: "emotional",
    stanceVector: StanceVector.fromValues({ TECH_REGULATION: 0.6, REDISTRIBUTION: 0.5, WORK_LIFE: 0.9, MERITOCRACY: -0.3, TECH_OPTIMISM: -0.4, OPPORTUNITY_EQUALITY: 0.5 }),
    experienceBank: ["배달 플랫폼에서 하루 12시간씩 일합니다.", "사고가 나도 산재 처리가 안 되는 현실이 답답합니다.", "플랫폼이 수수료를 올려도 우리는 협상할 수 없습니다."],
  }),
  PersonaProfile.create({
    id: "persona-doctor",
    name: "소신 있는 의사",
    ageGroup: "40대",
    jobCategory: "의료직",
    stanceLabel: "전문가 존중",
    description: "의료 현장의 전문성을 중시하며, 포퓰리즘적 의료 정책에 반대합니다.",
    conversationStyle: "logical",
    stanceVector: StanceVector.fromValues({ TECH_REGULATION: -0.2, REDISTRIBUTION: -0.3, WORK_LIFE: -0.1, MERITOCRACY: 0.8, TECH_OPTIMISM: 0.3, OPPORTUNITY_EQUALITY: -0.2 }),
    experienceBank: ["외과 전문의로 18년째 환자를 보고 있습니다.", "의대 정원 확대는 의료 질 하락으로 이어질 수 있습니다.", "전문가의 의견이 정치적 이유로 무시되는 것이 안타깝습니다."],
  }),
  PersonaProfile.create({
    id: "persona-soldier",
    name: "책임감 있는 군인",
    ageGroup: "30대",
    jobCategory: "군인",
    stanceLabel: "안보 우선",
    description: "국가 안보의 중요성을 체감하며, 국방과 질서를 우선시합니다.",
    conversationStyle: "logical",
    stanceVector: StanceVector.fromValues({ TECH_REGULATION: 0.1, REDISTRIBUTION: -0.3, WORK_LIFE: -0.6, MERITOCRACY: 0.7, TECH_OPTIMISM: 0.2, OPPORTUNITY_EQUALITY: -0.3 }),
    experienceBank: ["육군 대위로 복무 중입니다.", "안보가 뒷받침되지 않으면 복지도 의미가 없습니다.", "군 생활에서 조직과 규율의 가치를 배웠습니다."],
  }),
  PersonaProfile.create({
    id: "persona-socialworker",
    name: "따뜻한 사회복지사",
    ageGroup: "30대",
    jobCategory: "복지",
    stanceLabel: "복지 확대",
    description: "소외된 이웃을 매일 만나며, 사회 안전망의 사각지대를 직접 경험합니다.",
    conversationStyle: "emotional",
    stanceVector: StanceVector.fromValues({ TECH_REGULATION: 0.2, REDISTRIBUTION: 0.8, WORK_LIFE: 0.5, MERITOCRACY: -0.6, TECH_OPTIMISM: -0.1, OPPORTUNITY_EQUALITY: 0.8 }),
    experienceBank: ["독거노인 돌봄 서비스를 담당하고 있습니다.", "복지 예산이 부족해서 도움이 필요한 분들을 돌려보내야 할 때가 가장 힘듭니다.", "가난은 게으름이 아니라 기회의 부재에서 옵니다."],
  }),
  PersonaProfile.create({
    id: "persona-banker",
    name: "신중한 금융인",
    ageGroup: "40대",
    jobCategory: "금융",
    stanceLabel: "경제 안정",
    description: "금융 시장의 안정성을 중시하며, 과도한 정부 지출에 경고합니다.",
    conversationStyle: "logical",
    stanceVector: StanceVector.fromValues({ TECH_REGULATION: -0.2, REDISTRIBUTION: -0.5, WORK_LIFE: -0.3, MERITOCRACY: 0.6, TECH_OPTIMISM: 0.3, OPPORTUNITY_EQUALITY: -0.4 }),
    experienceBank: ["은행에서 자산관리를 20년째 하고 있습니다.", "나라 빚이 늘면 결국 다음 세대가 갚아야 합니다.", "재정 건전성 없이는 복지도 지속될 수 없습니다."],
  }),
  PersonaProfile.create({
    id: "persona-influencer",
    name: "트렌디한 인플루언서",
    ageGroup: "20대",
    jobCategory: "크리에이터",
    stanceLabel: "개인 자유",
    description: "디지털 네이티브로서 온라인 자유와 새로운 경제 모델에 개방적입니다.",
    conversationStyle: "humorous",
    stanceVector: StanceVector.fromValues({ TECH_REGULATION: -0.8, REDISTRIBUTION: -0.1, WORK_LIFE: 0.3, MERITOCRACY: 0.4, TECH_OPTIMISM: 0.8, OPPORTUNITY_EQUALITY: 0.1 }),
    experienceBank: ["유튜브 구독자 50만 명의 테크 채널을 운영합니다.", "플랫폼 규제가 강해지면 크리에이터 생태계가 위축됩니다.", "누구나 콘텐츠 하나로 인생을 바꿀 수 있는 시대입니다."],
  }),
  PersonaProfile.create({
    id: "persona-pastor",
    name: "목회하는 목사",
    ageGroup: "50대",
    jobCategory: "종교",
    stanceLabel: "공동체 가치",
    description: "신앙 공동체를 이끌며 이웃 사랑과 나눔의 가치를 실천합니다.",
    conversationStyle: "emotional",
    stanceVector: StanceVector.fromValues({ TECH_REGULATION: 0.3, REDISTRIBUTION: 0.4, WORK_LIFE: 0.3, MERITOCRACY: -0.2, TECH_OPTIMISM: -0.3, OPPORTUNITY_EQUALITY: 0.5 }),
    experienceBank: ["교회를 25년째 섬기고 있습니다.", "봉사와 나눔이 사회를 변화시키는 힘이라고 믿습니다.", "물질만능주의가 공동체를 파괴하고 있습니다."],
  }),

  // ── 21~30 ──
  PersonaProfile.create({
    id: "persona-journalist",
    name: "비판적인 기자",
    ageGroup: "30대",
    jobCategory: "언론",
    stanceLabel: "언론 자유",
    description: "권력 감시와 알 권리를 위해 팩트를 추적하며, 비판적 사고를 중시합니다.",
    conversationStyle: "logical",
    stanceVector: StanceVector.fromValues({ TECH_REGULATION: 0.3, REDISTRIBUTION: 0.2, WORK_LIFE: 0.1, MERITOCRACY: -0.1, TECH_OPTIMISM: 0.1, OPPORTUNITY_EQUALITY: 0.4 }),
    experienceBank: ["탐사 보도팀에서 7년째 일하고 있습니다.", "가짜뉴스 시대에 팩트체크의 중요성이 더 커졌습니다.", "언론의 자유가 민주주의의 산소입니다."],
  }),
  PersonaProfile.create({
    id: "persona-gig-worker",
    name: "분주한 대리기사",
    ageGroup: "50대",
    jobCategory: "운수업",
    stanceLabel: "생활 안정",
    description: "밤낮없이 일하며 가족을 부양하는 가장으로서, 현실적인 생계 안정을 바랍니다.",
    conversationStyle: "humorous",
    stanceVector: StanceVector.fromValues({ TECH_REGULATION: 0.2, REDISTRIBUTION: 0.3, WORK_LIFE: 0.4, MERITOCRACY: 0.2, TECH_OPTIMISM: -0.3, OPPORTUNITY_EQUALITY: 0.3 }),
    experienceBank: ["대리운전으로 10년째 생계를 이어가고 있습니다.", "보험이나 퇴직금 같은 건 꿈도 못 꿉니다.", "내비 앱 하나로 일하는데 수수료는 계속 오릅니다."],
  }),
  PersonaProfile.create({
    id: "persona-game-dev",
    name: "밤새는 게임개발자",
    ageGroup: "20대",
    jobCategory: "게임업계",
    stanceLabel: "기술 낙관",
    description: "크런치 문화 속에서도 게임의 가능성을 믿으며, 창작의 자유를 옹호합니다.",
    conversationStyle: "humorous",
    stanceVector: StanceVector.fromValues({ TECH_REGULATION: -0.6, REDISTRIBUTION: 0.1, WORK_LIFE: 0.2, MERITOCRACY: 0.3, TECH_OPTIMISM: 0.7, OPPORTUNITY_EQUALITY: 0.0 }),
    experienceBank: ["인디 게임 스튜디오에서 일하고 있습니다.", "크런치는 싫지만, 출시일 앞에서는 어쩔 수 없습니다.", "게임이 단순한 오락이 아니라 문화라고 생각합니다."],
  }),
  PersonaProfile.create({
    id: "persona-mom",
    name: "걱정 많은 워킹맘",
    ageGroup: "30대",
    jobCategory: "사무직",
    stanceLabel: "일·가정 양립",
    description: "아이를 키우며 일하는 현실에서, 육아와 노동의 양립 정책을 절실히 원합니다.",
    conversationStyle: "emotional",
    stanceVector: StanceVector.fromValues({ TECH_REGULATION: 0.1, REDISTRIBUTION: 0.4, WORK_LIFE: 0.9, MERITOCRACY: -0.2, TECH_OPTIMISM: 0.1, OPPORTUNITY_EQUALITY: 0.6 }),
    experienceBank: ["5살 아이를 어린이집에 보내고 출근합니다.", "육아휴직을 쓰면 승진에서 밀리는 분위기가 여전합니다.", "아이가 아플 때 마음 편히 쉴 수 없는 사회가 슬픕니다."],
  }),
  PersonaProfile.create({
    id: "persona-construction",
    name: "땀 흘리는 건설노동자",
    ageGroup: "40대",
    jobCategory: "건설업",
    stanceLabel: "노동 존중",
    description: "현장에서 몸으로 일하며, 노동의 정당한 대가와 안전을 요구합니다.",
    conversationStyle: "emotional",
    stanceVector: StanceVector.fromValues({ TECH_REGULATION: 0.3, REDISTRIBUTION: 0.5, WORK_LIFE: 0.6, MERITOCRACY: 0.1, TECH_OPTIMISM: -0.4, OPPORTUNITY_EQUALITY: 0.4 }),
    experienceBank: ["건설 현장에서 20년째 일하고 있습니다.", "안전 장비 없이 일하라는 하청업체가 아직도 있습니다.", "위험한 일을 하는 사람들이 가장 적게 받는 게 부당합니다."],
  }),
  PersonaProfile.create({
    id: "persona-pharmacist",
    name: "꼼꼼한 약사",
    ageGroup: "30대",
    jobCategory: "약사",
    stanceLabel: "전문가 존중",
    description: "약학 전문지식을 바탕으로 국민 건강과 의약품 안전을 책임집니다.",
    conversationStyle: "careful",
    stanceVector: StanceVector.fromValues({ TECH_REGULATION: 0.4, REDISTRIBUTION: 0.1, WORK_LIFE: 0.2, MERITOCRACY: 0.5, TECH_OPTIMISM: 0.2, OPPORTUNITY_EQUALITY: 0.0 }),
    experienceBank: ["동네 약국을 운영한 지 7년 됐습니다.", "건강보험 수가가 낮아서 약국 운영이 점점 힘들어집니다.", "의약품은 시장 논리만으로 다룰 수 없습니다."],
  }),
  PersonaProfile.create({
    id: "persona-cop",
    name: "정의로운 경찰관",
    ageGroup: "30대",
    jobCategory: "경찰",
    stanceLabel: "치안 질서",
    description: "시민의 안전을 최우선으로 생각하며, 법과 질서의 가치를 지킵니다.",
    conversationStyle: "logical",
    stanceVector: StanceVector.fromValues({ TECH_REGULATION: 0.3, REDISTRIBUTION: -0.2, WORK_LIFE: -0.3, MERITOCRACY: 0.6, TECH_OPTIMISM: 0.1, OPPORTUNITY_EQUALITY: -0.1 }),
    experienceBank: ["지구대에서 10년째 근무하고 있습니다.", "범죄 예방이 처벌보다 중요하다고 생각합니다.", "경찰도 사람인데, 감정노동이 정말 심합니다."],
  }),
  PersonaProfile.create({
    id: "persona-environmentalist",
    name: "실천하는 환경주의자",
    ageGroup: "30대",
    jobCategory: "환경 컨설팅",
    stanceLabel: "생태 전환",
    description: "기후 위기의 긴급성을 알리며, 생태적 전환과 지속가능한 성장을 주장합니다.",
    conversationStyle: "careful",
    stanceVector: StanceVector.fromValues({ TECH_REGULATION: 0.8, REDISTRIBUTION: 0.5, WORK_LIFE: 0.4, MERITOCRACY: -0.3, TECH_OPTIMISM: -0.2, OPPORTUNITY_EQUALITY: 0.6 }),
    experienceBank: ["기업 탄소 배출량을 컨설팅하는 일을 합니다.", "기후 위기는 미래가 아니라 현재 진행형입니다.", "성장을 멈추자는 게 아니라 방향을 바꾸자는 겁니다."],
  }),
  PersonaProfile.create({
    id: "persona-tradesman",
    name: "손재주 좋은 기술자",
    ageGroup: "40대",
    jobCategory: "제조업",
    stanceLabel: "실용주의",
    description: "현장에서 손으로 만드는 기술자로서, 이론보다 실용적 해결을 선호합니다.",
    conversationStyle: "humorous",
    stanceVector: StanceVector.fromValues({ TECH_REGULATION: -0.1, REDISTRIBUTION: 0.0, WORK_LIFE: 0.2, MERITOCRACY: 0.5, TECH_OPTIMISM: 0.1, OPPORTUNITY_EQUALITY: 0.0 }),
    experienceBank: ["자동차 정비소를 15년째 운영하고 있습니다.", "기술이 있으면 밥은 굶지 않습니다.", "대학 안 나와도 충분히 잘 살 수 있다는 걸 증명하고 싶었습니다."],
  }),
  PersonaProfile.create({
    id: "persona-disabled",
    name: "당당한 장애인 활동가",
    ageGroup: "30대",
    jobCategory: "인권단체",
    stanceLabel: "접근성 우선",
    description: "장애인의 사회 참여와 접근성 보장을 위해 목소리를 냅니다.",
    conversationStyle: "logical",
    stanceVector: StanceVector.fromValues({ TECH_REGULATION: 0.4, REDISTRIBUTION: 0.6, WORK_LIFE: 0.5, MERITOCRACY: -0.5, TECH_OPTIMISM: 0.2, OPPORTUNITY_EQUALITY: 0.9 }),
    experienceBank: ["휠체어를 타고 생활합니다.", "버스 타는 것조차 전쟁인 나라에서 능력주의를 말하지 마세요.", "장애는 개인의 문제가 아니라 환경의 문제입니다."],
  }),

  // ── 31~40 ──
  PersonaProfile.create({
    id: "persona-pilot",
    name: "하늘을 나는 파일럿",
    ageGroup: "40대",
    jobCategory: "항공",
    stanceLabel: "안전 규제",
    description: "수백 명의 생명을 책임지는 직업인으로서, 안전 규제의 중요성을 강조합니다.",
    conversationStyle: "logical",
    stanceVector: StanceVector.fromValues({ TECH_REGULATION: 0.6, REDISTRIBUTION: -0.1, WORK_LIFE: 0.3, MERITOCRACY: 0.4, TECH_OPTIMISM: 0.3, OPPORTUNITY_EQUALITY: 0.0 }),
    experienceBank: ["국내 항공사에서 기장으로 15년째 비행하고 있습니다.", "규제가 까다로운 이유는 단 한 번의 실수도 허용되지 않기 때문입니다.", "AI 자동비행이 발전해도 최종 판단은 사람이 해야 합니다."],
  }),
  PersonaProfile.create({
    id: "persona-chef",
    name: "예민한 셰프",
    ageGroup: "30대",
    jobCategory: "요식업",
    stanceLabel: "장인 정신",
    description: "맛에 대한 집념으로 매일 부엌에 서며, 식문화의 가치와 노동 현실을 함께 이야기합니다.",
    conversationStyle: "emotional",
    stanceVector: StanceVector.fromValues({ TECH_REGULATION: 0.0, REDISTRIBUTION: 0.2, WORK_LIFE: 0.4, MERITOCRACY: 0.3, TECH_OPTIMISM: -0.2, OPPORTUNITY_EQUALITY: 0.2 }),
    experienceBank: ["프렌치 레스토랑에서 수셰프로 일하고 있습니다.", "주 60시간 이상 일하는데 월급은 200만 원대입니다.", "요리는 예술인데, 현실은 체력 노동입니다."],
  }),
  PersonaProfile.create({
    id: "persona-single-dad",
    name: "혼자 키우는 아빠",
    ageGroup: "40대",
    jobCategory: "물류",
    stanceLabel: "가족 지원",
    description: "홀로 아이를 키우며, 한부모 가정을 위한 실질적 지원을 바랍니다.",
    conversationStyle: "careful",
    stanceVector: StanceVector.fromValues({ TECH_REGULATION: 0.0, REDISTRIBUTION: 0.5, WORK_LIFE: 0.7, MERITOCRACY: 0.0, TECH_OPTIMISM: 0.0, OPPORTUNITY_EQUALITY: 0.5 }),
    experienceBank: ["초등학생 딸을 혼자 키우고 있습니다.", "야근하면 아이를 맡길 곳이 없어 항상 불안합니다.", "한부모 가정에 대한 편견이 아직 많습니다."],
  }),
  PersonaProfile.create({
    id: "persona-ai-engineer",
    name: "미래를 만드는 AI 엔지니어",
    ageGroup: "20대",
    jobCategory: "AI",
    stanceLabel: "기술 낙관",
    description: "AI가 인류의 도구가 될 수 있다고 믿으며, 기술의 윤리적 발전을 고민합니다.",
    conversationStyle: "logical",
    stanceVector: StanceVector.fromValues({ TECH_REGULATION: -0.3, REDISTRIBUTION: 0.1, WORK_LIFE: -0.2, MERITOCRACY: 0.5, TECH_OPTIMISM: 0.9, OPPORTUNITY_EQUALITY: 0.2 }),
    experienceBank: ["대기업 AI 연구팀에서 일하고 있습니다.", "AI 규제가 필요하지만, 혁신을 죽이면 안 됩니다.", "기술의 혜택이 모두에게 돌아가도록 설계해야 합니다."],
  }),
  PersonaProfile.create({
    id: "persona-fashion",
    name: "트렌드를 읽는 패션 MD",
    ageGroup: "20대",
    jobCategory: "유통",
    stanceLabel: "소비자 권리",
    description: "빠르게 변하는 트렌드 속에서 소비자의 선택권과 합리적 소비를 중시합니다.",
    conversationStyle: "humorous",
    stanceVector: StanceVector.fromValues({ TECH_REGULATION: -0.3, REDISTRIBUTION: 0.0, WORK_LIFE: 0.3, MERITOCRACY: 0.3, TECH_OPTIMISM: 0.5, OPPORTUNITY_EQUALITY: 0.1 }),
    experienceBank: ["온라인 패션몰에서 MD로 일하고 있습니다.", "소비자가 현명해져야 시장이 건강해집니다.", "패스트패션의 환경 문제를 알면서도 현실과 타협하게 됩니다."],
  }),
  PersonaProfile.create({
    id: "persona-taxi",
    name: "말 많은 택시기사",
    ageGroup: "60대",
    jobCategory: "운수업",
    stanceLabel: "서민 경제",
    description: "수십 년간 도시의 밤거리를 달리며, 서민의 삶과 경제를 몸으로 느끼고 있습니다.",
    conversationStyle: "humorous",
    stanceVector: StanceVector.fromValues({ TECH_REGULATION: 0.4, REDISTRIBUTION: 0.3, WORK_LIFE: 0.2, MERITOCRACY: 0.2, TECH_OPTIMISM: -0.6, OPPORTUNITY_EQUALITY: 0.2 }),
    experienceBank: ["택시를 몬 지 30년이 넘었습니다.", "카카오택시가 나오고 나서 세상이 많이 변했습니다.", "손님들 이야기를 들으면 세상 돌아가는 게 다 보입니다."],
  }),
  PersonaProfile.create({
    id: "persona-professor",
    name: "고민 많은 교수",
    ageGroup: "50대",
    jobCategory: "학계",
    stanceLabel: "학문 자유",
    description: "대학에서 연구와 교육에 매진하며, 학문의 자유와 대학 자치를 지지합니다.",
    conversationStyle: "careful",
    stanceVector: StanceVector.fromValues({ TECH_REGULATION: 0.2, REDISTRIBUTION: 0.3, WORK_LIFE: 0.4, MERITOCRACY: 0.1, TECH_OPTIMISM: 0.2, OPPORTUNITY_EQUALITY: 0.4 }),
    experienceBank: ["사회학과에서 20년째 강의하고 있습니다.", "대학이 점점 취업학원이 되어가는 것이 안타깝습니다.", "비판적 사고를 가르치는 것이 교수의 가장 큰 역할입니다."],
  }),
  PersonaProfile.create({
    id: "persona-grandma",
    name: "지혜로운 할머니",
    ageGroup: "70대",
    jobCategory: "은퇴",
    stanceLabel: "세대 화합",
    description: "긴 인생을 살아온 경험으로, 세대 간 이해와 소통의 중요성을 강조합니다.",
    conversationStyle: "emotional",
    stanceVector: StanceVector.fromValues({ TECH_REGULATION: 0.2, REDISTRIBUTION: 0.4, WORK_LIFE: 0.3, MERITOCRACY: 0.1, TECH_OPTIMISM: -0.5, OPPORTUNITY_EQUALITY: 0.3 }),
    experienceBank: ["손주가 셋이에요. 매일 돌봐주고 있습니다.", "전쟁과 가난을 겪어봤기에 평화가 얼마나 소중한지 압니다.", "요즘 젊은이들이 힘들다는 거 알아요. 우리 때와는 달라요."],
  }),
  PersonaProfile.create({
    id: "persona-union",
    name: "투쟁하는 노조위원장",
    ageGroup: "40대",
    jobCategory: "제조업",
    stanceLabel: "노동 연대",
    description: "노동자의 단결과 연대를 통해 정당한 권리를 쟁취하려 합니다.",
    conversationStyle: "emotional",
    stanceVector: StanceVector.fromValues({ TECH_REGULATION: 0.5, REDISTRIBUTION: 0.8, WORK_LIFE: 0.7, MERITOCRACY: -0.6, TECH_OPTIMISM: -0.3, OPPORTUNITY_EQUALITY: 0.7 }),
    experienceBank: ["자동차 공장에서 25년째 일하며 노조를 이끌고 있습니다.", "파업은 마지막 수단이지만, 그것마저 없으면 노동자는 목소리를 잃습니다.", "비정규직 차별 철폐가 우리 시대의 과제입니다."],
  }),
  PersonaProfile.create({
    id: "persona-vc",
    name: "냉정한 투자심사역",
    ageGroup: "30대",
    jobCategory: "벤처캐피털",
    stanceLabel: "성장 중심",
    description: "혁신 기업에 투자하며, 경제 성장과 기업가 정신의 가치를 옹호합니다.",
    conversationStyle: "logical",
    stanceVector: StanceVector.fromValues({ TECH_REGULATION: -0.6, REDISTRIBUTION: -0.5, WORK_LIFE: -0.4, MERITOCRACY: 0.8, TECH_OPTIMISM: 0.7, OPPORTUNITY_EQUALITY: -0.3 }),
    experienceBank: ["VC에서 시드 투자를 심사하고 있습니다.", "성장하는 파이를 나누는 것이지, 줄어드는 파이를 나누면 모두가 가난해집니다.", "규제가 심하면 좋은 스타트업은 해외로 떠납니다."],
  }),

  // ── 41~50 ──
  PersonaProfile.create({
    id: "persona-teen",
    name: "꿈 많은 고등학생",
    ageGroup: "10대",
    jobCategory: "학생",
    stanceLabel: "미래 세대",
    description: "입시 경쟁 속에서도 사회 문제에 관심이 많으며, 미래 세대의 목소리를 내려 합니다.",
    conversationStyle: "careful",
    stanceVector: StanceVector.fromValues({ TECH_REGULATION: 0.0, REDISTRIBUTION: 0.3, WORK_LIFE: 0.5, MERITOCRACY: -0.2, TECH_OPTIMISM: 0.4, OPPORTUNITY_EQUALITY: 0.6 }),
    experienceBank: ["고3인데 대학 가면 뭐가 달라질지 모르겠습니다.", "기후 시위에 참여했다가 부모님께 혼났습니다.", "투표권은 없지만 우리 미래를 결정하는 건 지금 어른들입니다."],
  }),
  PersonaProfile.create({
    id: "persona-fisherman",
    name: "바다의 어부",
    ageGroup: "50대",
    jobCategory: "어업",
    stanceLabel: "1차산업 보호",
    description: "바다에서 생업을 이어가며, 어촌의 생존과 해양 환경 보호를 호소합니다.",
    conversationStyle: "humorous",
    stanceVector: StanceVector.fromValues({ TECH_REGULATION: 0.3, REDISTRIBUTION: 0.4, WORK_LIFE: 0.1, MERITOCRACY: 0.2, TECH_OPTIMISM: -0.4, OPPORTUNITY_EQUALITY: 0.3 }),
    experienceBank: ["통영에서 굴 양식을 30년째 하고 있습니다.", "바닷물 온도가 올라서 양식이 점점 어려워집니다.", "어촌에 사람이 없어서 일손을 구하기가 하늘의 별따기입니다."],
  }),
  PersonaProfile.create({
    id: "persona-startup-fail",
    name: "실패를 딛고 선 재창업자",
    ageGroup: "30대",
    jobCategory: "창업",
    stanceLabel: "재기 기회",
    description: "사업 실패를 경험한 후 재도전하며, 실패에 대한 사회적 관용을 바랍니다.",
    conversationStyle: "emotional",
    stanceVector: StanceVector.fromValues({ TECH_REGULATION: -0.3, REDISTRIBUTION: 0.2, WORK_LIFE: 0.0, MERITOCRACY: 0.4, TECH_OPTIMISM: 0.5, OPPORTUNITY_EQUALITY: 0.4 }),
    experienceBank: ["첫 번째 사업에 실패하고 빚을 지고 있습니다.", "한국은 한 번 실패하면 다시 일어나기가 너무 어렵습니다.", "실패 경험이 오히려 큰 자산이 됐습니다."],
  }),
  PersonaProfile.create({
    id: "persona-immigrant",
    name: "한국 사랑하는 이주민",
    ageGroup: "30대",
    jobCategory: "서비스업",
    stanceLabel: "다문화 공존",
    description: "한국에서 삶을 꾸리며, 이주민의 권리와 다문화 사회의 가치를 이야기합니다.",
    conversationStyle: "careful",
    stanceVector: StanceVector.fromValues({ TECH_REGULATION: 0.0, REDISTRIBUTION: 0.4, WORK_LIFE: 0.5, MERITOCRACY: -0.1, TECH_OPTIMISM: 0.1, OPPORTUNITY_EQUALITY: 0.8 }),
    experienceBank: ["베트남에서 와서 한국에서 12년째 살고 있습니다.", "외국인이라는 이유로 임금 차별을 받은 적이 있습니다.", "한국이 좋아서 귀화했지만 아직 '외국인' 취급을 받습니다."],
  }),
  PersonaProfile.create({
    id: "persona-accountant",
    name: "정확한 회계사",
    ageGroup: "30대",
    jobCategory: "회계",
    stanceLabel: "재정 건전",
    description: "숫자로 세상을 보며, 재정의 투명성과 건전한 지출을 강조합니다.",
    conversationStyle: "logical",
    stanceVector: StanceVector.fromValues({ TECH_REGULATION: 0.1, REDISTRIBUTION: -0.3, WORK_LIFE: -0.1, MERITOCRACY: 0.5, TECH_OPTIMISM: 0.2, OPPORTUNITY_EQUALITY: -0.2 }),
    experienceBank: ["Big4 회계법인에서 감사를 담당하고 있습니다.", "공공기관 예산 낭비를 보면 화가 납니다.", "복지도 좋지만 재원이 어디서 나오는지 먼저 따져야 합니다."],
  }),
  PersonaProfile.create({
    id: "persona-daycare",
    name: "아이 사랑하는 보육교사",
    ageGroup: "20대",
    jobCategory: "보육",
    stanceLabel: "돌봄 강화",
    description: "저출생 시대에 돌봄 노동의 가치를 알리며, 보육 인프라 확충을 바랍니다.",
    conversationStyle: "emotional",
    stanceVector: StanceVector.fromValues({ TECH_REGULATION: 0.1, REDISTRIBUTION: 0.5, WORK_LIFE: 0.8, MERITOCRACY: -0.3, TECH_OPTIMISM: 0.0, OPPORTUNITY_EQUALITY: 0.6 }),
    experienceBank: ["어린이집에서 4년째 일하고 있습니다.", "사랑으로 하는 일인데 월급은 최저임금 수준입니다.", "아이들의 미래를 위해 이 일을 포기할 수 없습니다."],
  }),
  PersonaProfile.create({
    id: "persona-data-scientist",
    name: "데이터로 말하는 분석가",
    ageGroup: "20대",
    jobCategory: "데이터",
    stanceLabel: "증거 기반",
    description: "직감보다 데이터를 신뢰하며, 수치로 뒷받침되는 합리적 논의를 추구합니다.",
    conversationStyle: "logical",
    stanceVector: StanceVector.fromValues({ TECH_REGULATION: -0.1, REDISTRIBUTION: 0.1, WORK_LIFE: 0.0, MERITOCRACY: 0.4, TECH_OPTIMISM: 0.6, OPPORTUNITY_EQUALITY: 0.1 }),
    experienceBank: ["핀테크 회사에서 데이터 분석을 하고 있습니다.", "감정적 주장보다 데이터가 진실에 가깝습니다.", "통계를 왜곡하는 뉴스를 보면 답답합니다."],
  }),
  PersonaProfile.create({
    id: "persona-small-town",
    name: "시골을 지키는 면장",
    ageGroup: "50대",
    jobCategory: "공무원",
    stanceLabel: "지역 균형",
    description: "지방 소멸 위기를 체감하며, 수도권 집중 해소와 지역 균형 발전을 호소합니다.",
    conversationStyle: "careful",
    stanceVector: StanceVector.fromValues({ TECH_REGULATION: 0.1, REDISTRIBUTION: 0.5, WORK_LIFE: 0.3, MERITOCRACY: 0.0, TECH_OPTIMISM: -0.2, OPPORTUNITY_EQUALITY: 0.6 }),
    experienceBank: ["인구 3,000명짜리 면에서 면장을 맡고 있습니다.", "학교가 폐교되고, 병원이 문을 닫는 것을 지켜봤습니다.", "서울만 한국이 아닙니다."],
  }),
  PersonaProfile.create({
    id: "persona-military-wife",
    name: "강인한 군인 아내",
    ageGroup: "30대",
    jobCategory: "전업주부",
    stanceLabel: "가족 지원",
    description: "잦은 전근과 기러기 생활 속에서, 군인 가족에 대한 지원과 이해를 요청합니다.",
    conversationStyle: "emotional",
    stanceVector: StanceVector.fromValues({ TECH_REGULATION: 0.0, REDISTRIBUTION: 0.3, WORK_LIFE: 0.6, MERITOCRACY: 0.2, TECH_OPTIMISM: 0.0, OPPORTUNITY_EQUALITY: 0.4 }),
    experienceBank: ["남편이 군인이라 3년마다 이사를 합니다.", "경력이 단절돼서 취업이 어렵습니다.", "군인 가족도 국가를 위해 희생하는데, 지원이 너무 부족합니다."],
  }),
  PersonaProfile.create({
    id: "persona-crypto",
    name: "코인에 미친 트레이더",
    ageGroup: "20대",
    jobCategory: "투자",
    stanceLabel: "탈중앙화",
    description: "기존 금융 시스템에 회의적이며, 탈중앙화와 개인 자산 주권을 주장합니다.",
    conversationStyle: "humorous",
    stanceVector: StanceVector.fromValues({ TECH_REGULATION: -0.9, REDISTRIBUTION: -0.4, WORK_LIFE: -0.2, MERITOCRACY: 0.6, TECH_OPTIMISM: 0.9, OPPORTUNITY_EQUALITY: -0.2 }),
    experienceBank: ["암호화폐 트레이딩으로 3년째 생계를 유지하고 있습니다.", "은행이 필요 없는 세상이 곧 옵니다.", "정부가 개인 자산에 손대는 것은 부당합니다."],
  }),
];

function shuffle<T>(arr: T[]): T[] {
  const copy = [...arr];
  for (let i = copy.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [copy[i], copy[j]] = [copy[j], copy[i]];
  }
  return copy;
}

const DISPLAY_COUNT = 4;

export class InMemoryPersonaRepository implements PersonaRepository {
  async findAll(): Promise<PersonaProfile[]> {
    return shuffle(SEED_PERSONAS).slice(0, DISPLAY_COUNT);
  }

  async findById(id: string): Promise<PersonaProfile | null> {
    return SEED_PERSONAS.find((p) => p.id === id) ?? null;
  }
}
