import {
  ApplyDownshiftUseCase,
  ApplyRecoveryRoutineUseCase,
  BuildJointSummaryCardUseCase,
  BuildMatchCardUseCase,
  BuildNotificationUseCase,
  CalculatePrecisionUseCase,
  CalculateStanceDriftUseCase,
  CheckFeatureFlagUseCase,
  CheckMatchingPoolUseCase,
  CheckRetakeLimitUseCase,
  CheckToneUseCase,
  CollectPeakEndKPIUseCase,
  CreateHighlightByTapUseCase,
  CreateHighlightUseCase,
  DetermineHomeStateUseCase,
  DetermineNextStepUseCase,
  DetermineReflectionPolicyUseCase,
  DetectBadExperienceUseCase,
  EvaluateJitaiRulesUseCase,
  ExcludeDialogueFromRecordUseCase,
  ExtractBlindSpotUseCase,
  GenerateConversationTrailerUseCase,
  GeneratePersonaResponseUseCase,
  GenerateReflectionQuizUseCase,
  GenerateReplayCardUseCase,
  GenerateShareCardUseCase,
  GetCoachSuggestionsUseCase,
  GetExperimentVariantUseCase,
  GetMicrocopyForContextUseCase,
  GetScaffoldForStepUseCase,
  GetTuringStatsUseCase,
  HandleThoughtChangeUseCase,
  ManageDriftPreferenceUseCase,
  ManageNotificationPreferenceUseCase,
  RecordDeclineReasonUseCase,
  RequestNotificationPermissionUseCase,
  ResumePersonaConversationUseCase,
  RevealGiftMessageUseCase,
  SaveCommonGroundUseCase,
  SaveNextQuestionUseCase,
  SavePersonaUseCase,
  SelectEnergyLevelUseCase,
  SelectOnboardingModeUseCase,
  SelectPersonaUseCase,
  SendDriftNotificationUseCase,
  SegmentTextUseCase,
  SubmitMutualVerificationUseCase,
  SubmitQuizAnswerAndTextUseCase,
  SubmitRoleplaySteelmanUseCase,
  SubmitTuringGuessUseCase,
  SuggestReceptivenessTemplateUseCase,
  TrackEventUseCase,
  UpdatePerspectivePassportUseCase,
  WriteGiftMessageUseCase,
} from "@/application/use-cases";
import { InMemoryEventEmitter } from "../external/in-memory-event-emitter";
import type { CoreDependencies } from "./container-core";

export function createExtendedUseCases(deps: CoreDependencies) {
  return {
    selectOnboardingModeUseCase: new SelectOnboardingModeUseCase({
      questionBank: deps.questionBank,
    }),
    calculatePrecisionUseCase: new CalculatePrecisionUseCase(),
    checkRetakeLimitUseCase: new CheckRetakeLimitUseCase(),
    generateShareCardUseCase: new GenerateShareCardUseCase(),
    determineNextStepUseCase: new DetermineNextStepUseCase(),
    buildMatchCardUseCase: new BuildMatchCardUseCase(),
    selectEnergyLevelUseCase: new SelectEnergyLevelUseCase(),
    recordDeclineReasonUseCase: new RecordDeclineReasonUseCase(),
    getScaffoldForStepUseCase: new GetScaffoldForStepUseCase(),
    getCoachSuggestionsUseCase: new GetCoachSuggestionsUseCase(),
    createHighlightUseCase: new CreateHighlightUseCase(),
    checkToneUseCase: new CheckToneUseCase(),
    suggestReceptivenessTemplateUseCase:
      new SuggestReceptivenessTemplateUseCase({
        facilitator: deps.facilitator,
      }),
    generateReflectionQuizUseCase: new GenerateReflectionQuizUseCase({
      summaryGenerator: deps.summaryGenerator,
    }),
    submitQuizAnswerUseCase: new SubmitQuizAnswerAndTextUseCase(),
    submitMutualVerificationUseCase: new SubmitMutualVerificationUseCase(),
    submitRoleplaySteelmanUseCase: new SubmitRoleplaySteelmanUseCase(),
    saveCommonGroundUseCase: new SaveCommonGroundUseCase(),
    determineReflectionPolicyUseCase: new DetermineReflectionPolicyUseCase(),
    evaluateJitaiRulesUseCase: new EvaluateJitaiRulesUseCase(),
    applyDownshiftUseCase: new ApplyDownshiftUseCase(),
    buildJointSummaryCardUseCase: new BuildJointSummaryCardUseCase(),
    writeGiftMessageUseCase: new WriteGiftMessageUseCase(),
    revealGiftMessageUseCase: new RevealGiftMessageUseCase(),
    extractBlindSpotUseCase: new ExtractBlindSpotUseCase(),
    collectPeakEndKPIUseCase: new CollectPeakEndKPIUseCase(),
    saveNextQuestionUseCase: new SaveNextQuestionUseCase(),
    detectBadExperienceUseCase: new DetectBadExperienceUseCase(),
    applyRecoveryRoutineUseCase: new ApplyRecoveryRoutineUseCase(),
    excludeDialogueFromRecordUseCase: new ExcludeDialogueFromRecordUseCase(),
    determineHomeStateUseCase: new DetermineHomeStateUseCase(),
    generateReplayCardUseCase: new GenerateReplayCardUseCase(),
    updatePerspectivePassportUseCase: new UpdatePerspectivePassportUseCase(),
    handleThoughtChangeUseCase: new HandleThoughtChangeUseCase(),
    buildNotificationUseCase: new BuildNotificationUseCase(),
    manageNotificationPreferenceUseCase:
      new ManageNotificationPreferenceUseCase(),
    requestNotificationPermissionUseCase:
      new RequestNotificationPermissionUseCase(),
    trackEventUseCase: new TrackEventUseCase({
      eventEmitter: new InMemoryEventEmitter(),
    }),
    getMicrocopyForContextUseCase: new GetMicrocopyForContextUseCase(),
    checkFeatureFlagUseCase: new CheckFeatureFlagUseCase(),
    getExperimentVariantUseCase: new GetExperimentVariantUseCase(),
    calculateStanceDriftUseCase: new CalculateStanceDriftUseCase(),
    manageDriftPreferenceUseCase: new ManageDriftPreferenceUseCase(),
    sendDriftNotificationUseCase: new SendDriftNotificationUseCase(),
    checkMatchingPoolUseCase: new CheckMatchingPoolUseCase(),
    submitTuringGuessUseCase: new SubmitTuringGuessUseCase({
      turingGuessRepository: deps.turingGuessRepository,
      resolveActualSpeaker: deps.resolveActualSpeaker,
    }),
    getTuringStatsUseCase: new GetTuringStatsUseCase(
      deps.turingGuessRepository,
    ),
    selectPersonaUseCase: new SelectPersonaUseCase(deps.personaRepository),
    generatePersonaResponseUseCase: new GeneratePersonaResponseUseCase({
      personaRepository: deps.personaRepository,
      personaDialogueGenerator: deps.personaDialogueGenerator,
    }),
    savePersonaUseCase: new SavePersonaUseCase(deps.savedPersonaRepository),
    resumePersonaConversationUseCase: new ResumePersonaConversationUseCase(
      deps.savedPersonaRepository,
    ),
    segmentTextUseCase: new SegmentTextUseCase(deps.textSegmenter),
    createHighlightByTapUseCase: new CreateHighlightByTapUseCase(),
    generateConversationTrailerUseCase: new GenerateConversationTrailerUseCase({
      trailerGenerator: deps.trailerGenerator,
    }),
  };
}
